services:
    MajidMvulle\Bundle\UtilityBundle\EventListener\OptionsAnnotationListener:
        arguments:
            - '@annotations.reader'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    MajidMvulle\Bundle\UtilityBundle\Form\CityType:
        tags:
           - { name: form.type }

    majidmvulle.utility.form.city: '@MajidMvulle\Bundle\UtilityBundle\Form\CityType'

    MajidMvulle\Bundle\UtilityBundle\Form\GenderType:
        tags:
           - { name: form.type }

    majidmvulle.utility.form.gender: '@MajidMvulle\Bundle\UtilityBundle\Form\GenderType'

    MajidMvulle\Bundle\UtilityBundle\Form\LanguageType:
        tags:
           - { name: form.type }

    majidmvulle.utility.form.language: '@MajidMvulle\Bundle\UtilityBundle\Form\LanguageType'

    MajidMvulle\Bundle\UtilityBundle\Form\MobileNumberType:
        tags:
           - { name: form.type }

    majidmvulle.utility.form.mobile_number: '@MajidMvulle\Bundle\UtilityBundle\Form\MobileNumberType'

    MajidMvulle\Bundle\UtilityBundle\Form\PhoneNumberType:
        tags:
           - { name: form.type }

    majidmvulle.utility.form.phone_number: '@MajidMvulle\Bundle\UtilityBundle\Form\PhoneNumberType'

    MajidMvulle\Bundle\UtilityBundle\Request\ParamConverter\SecureDoctrineParamConverter:
        arguments:
            - '@doctrine'
            - '@security.authorization_checker'
        tags:
            - { name: request.param_converter, priority: 1 }

    MajidMvulle\Bundle\UtilityBundle\Twig\Markdown:
        class: MajidMvulle\Bundle\UtilityBundle\Twig\Markdown

    majidmvulle.utility.twig.markdown: '@MajidMvulle\Bundle\UtilityBundle\Twig\Markdown'

    MajidMvulle\Bundle\UtilityBundle\Twig\MarkdownTwigExtension:
        arguments:
           - '@MajidMvulle\Bundle\UtilityBundle\Twig\Markdown'
        tags:
            - { name: twig.extension }
        public: false

    majidmvulle.utility.twig.markdown_extension: '@MajidMvulle\Bundle\UtilityBundle\Twig\MarkdownTwigExtension'

    MajidMvulle\Bundle\UtilityBundle\TwilioManager:
        arguments:
            - '@kernel'
            - '%majidmvulle.utility.twilio.sid%'
            - '%majidmvulle.utility.twilio.token%'
            - '%majidmvulle.utility.twilio.from_number%'
            - '%majidmvulle.utility.twilio.verification_sid%'
            - '%majidmvulle.utility.twilio.locale%'
            - '%majidmvulle.utility.twilio.region%'

    majidmvulle.utility.twilio_manager: '@MajidMvulle\Bundle\UtilityBundle\TwilioManager'
